#!/usr/bin/env bash

CTAGS_CMD='ctags'

main() {
  # Skip if currently rebasing
  test -d .git/rebase-merge && exit 0

  lckdo -W 10 .tags.lock $CTAGS_CMD -L <(git ls-files) -f .tags >/dev/null 2>&1
}

main >/dev/null 2>/dev/null &
